use_frameworks!

platform :ios, '9.0'

target 'CapsuleDesignSystem_Example' do
  pod 'CapsuleDesignSystem', :path => '../'

  target 'CapsuleDesignSystem_Tests' do
    inherit! :search_paths

    
  end
end
